# Generated by Django 4.2.3 on 2023-07-05 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='driver',
            name='driver_license',
            field=models.BinaryField(),
        ),
        migrations.AlterField(
            model_name='driver',
            name='straxovka',
            field=models.BinaryField(),
        ),
    ]
