# Generated by Django 4.2.3 on 2023-07-06 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='driver',
            name='car_type',
            field=models.CharField(blank=True, choices=[('big', 'big'), ('middle', 'middle'), ('minivan', 'minivan')], default='big', max_length=100),
        ),
    ]
