# Generated by Django 4.2.1 on 2023-07-07 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='per_km',
            field=models.CharField(default=1, max_length=10),
            preserve_default=False,
        ),
    ]
