# Generated by Django 4.2.1 on 2023-07-07 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_company_per_km'),
    ]

    operations = [
        migrations.AddField(
            model_name='driver',
            name='per_km',
            field=models.CharField(blank=True, default='', max_length=10),
        ),
        migrations.AlterField(
            model_name='company',
            name='per_km',
            field=models.CharField(blank=True, default='', max_length=10),
        ),
    ]
