# Generated by Django 4.2.3 on 2023-07-03 13:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_company3ver_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company3ver',
            name='email',
        ),
    ]
