# Generated by Django 4.2.2 on 2023-07-04 18:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('receiver_name', models.CharField(max_length=200)),
                ('receiver_surname', models.CharField(max_length=200)),
                ('receiver_number', models.CharField(max_length=200)),
                ('origin', models.FloatField()),
                ('destination', models.FloatField()),
                ('date_until', models.DateTimeField()),
                ('delivery_type', models.CharField(max_length=200)),
                ('sender', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='FirstOrder',
            fields=[
                ('order_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='order.order')),
                ('car_type', models.CharField(max_length=200)),
            ],
            bases=('order.order',),
        ),
        migrations.CreateModel(
            name='SecondOrder',
            fields=[
                ('order_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='order.order')),
                ('cargo_type', models.CharField(max_length=200)),
                ('weight', models.IntegerField()),
                ('volume_x', models.IntegerField()),
                ('volume_y', models.IntegerField()),
                ('volume_z', models.IntegerField()),
            ],
            bases=('order.order',),
        ),
    ]
