# Generated by Django 4.2.3 on 2023-07-06 19:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderStack',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.UUIDField(unique=True)),
                ('type', models.CharField(choices=[('FT', 'FIRST'), ('ST', 'SECOND')], max_length=2)),
                ('status', models.CharField(choices=[('P', 'PENDING'), ('F', 'DRIVER_FOUND'), ('A', 'ADOPTED'), ('O', 'ON_THE_WAY'), ('D', 'DELIVERED')], default='P', max_length=1)),
                ('driver_type', models.CharField(choices=[('IN', 'INDIVIDUAL'), ('CO', 'COMPANY_DRIVER')], max_length=2, null=True)),
                ('driver_id', models.IntegerField(null=True)),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SecondOrder',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('receiver_name', models.CharField(max_length=200)),
                ('receiver_surname', models.CharField(max_length=200)),
                ('receiver_number', models.CharField(max_length=200)),
                ('origin_lon', models.FloatField()),
                ('origin_lat', models.FloatField()),
                ('destination_lon', models.FloatField()),
                ('destination_lat', models.FloatField()),
                ('date_until', models.DateTimeField()),
                ('delivery_type', models.CharField(max_length=200)),
                ('cargo_type', models.CharField(max_length=200)),
                ('weight', models.IntegerField()),
                ('volume_x', models.IntegerField()),
                ('volume_y', models.IntegerField()),
                ('volume_z', models.IntegerField()),
                ('sender', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
                'unique_together': {('id',)},
            },
        ),
        migrations.CreateModel(
            name='FirstOrder',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('receiver_name', models.CharField(max_length=200)),
                ('receiver_surname', models.CharField(max_length=200)),
                ('receiver_number', models.CharField(max_length=200)),
                ('origin_lon', models.FloatField()),
                ('origin_lat', models.FloatField()),
                ('destination_lon', models.FloatField()),
                ('destination_lat', models.FloatField()),
                ('date_until', models.DateTimeField()),
                ('delivery_type', models.CharField(max_length=200)),
                ('car_type', models.CharField(choices=[('big', 'big'), ('middle', 'middle'), ('minivan', 'minivan')], default='big', max_length=10)),
                ('sender', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
                'unique_together': {('id',)},
            },
        ),
    ]
