# Generated by Django 4.2.3 on 2023-07-06 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderstack',
            name='driver_id',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='orderstack',
            name='driver_type',
            field=models.CharField(choices=[('IN', 'INDIVIDUAL'), ('CO', 'COMPANY_DRIVER')], max_length=2, null=True),
        ),
    ]
